apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: jwebgames
      service: postgres
  template:
    metadata:
      labels:
        app: jwebgames
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "webapi"
            - name: POSTGRES_PASSWORD
              value: "webapi"
            - name: POSTGRES_DB
              value: "webapi"
            - name: PGDATA
              value: /var/lib/postgresql/data/data
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: postgres-port
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: postgres-port
            initialDelaySeconds: 10
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
