apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jwebgames
      service: webapi
  template:
    metadata:
      labels:
        app: jwebgames
        service: webapi
    spec:
      containers:
        - name: webapi
          image: gcr.io/perso-206820/jwebgames-webapi:v1
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 3000
          env:
            - name: WEBAPI_HOST
              value: "0.0.0.0"
            - name: WEBAPI_PORT
              value: "3000"
            - name: PRODUCTION
              value: "false"
            - name: MESSAGER_PULL_ADDR
              value: $(MESSAGER_PORT_22549_TCP)
            - name: MESSAGE_PUB_ADDR
              value: $(MESSAGER_PORT_22550_TCP)
            - name: WEBAPI_LOG_LEVEL
              value: DEBUG
          resources:
            limits:
              cpu: 0.2
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /status
              port: http-port
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http-port
            initialDelaySeconds: 10
