apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapi-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: webapi
          servicePort: 80
