apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: jwebgames
      service: webapi
  template:
    metadata:
      labels:
        app: jwebgames
        service: webapi
    spec:
      containers:
        - name: webapi
          image: gcr.io/perso-206820/jwebgames-webapi:v1
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 3000
          env:
            - name: WEBAPI_HOST
              value: "0.0.0.0"
            - name: WEBAPI_PORT
              value: "3000"
            - name: PRODUCTION
              value: "true"
            - name: MESSAGER_PULL_ADDR
              value: "tcp://messager:22549"
            - name: MESSAGE_PUB_ADDR
              value: "tcp://messager:22550"
            - name: REDIS_DNS
              value: "redis://redis:6379/0"
            - name: PG_HOST
              value: "postgres"
            - name: PG_USER
              value: "webapi"
            - name: PG_PASSWORD
              value: "webapi"
            - name: PG_DATABASE
              value: "webapi"
            - name: WEBAPI_LOG_LEVEL
              value: "DEBUG"
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /status
              port: http-port
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: http-port
            initialDelaySeconds: 10
